name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # This triggers the workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Prepare zip folder
        run: |
          mkdir cidgravitygateway
          rsync -av --progress . ./cidgravitygateway --exclude node_modules --exclude .git --exclude cidgravitygateway --exclude .github --exclude .vscode
          zip -r nextcloud-app.zip cidgravitygateway

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: nextcloud-app.zip
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
