name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

      - name: Prepare zip folder
        run: |
          mkdir cidgravitygateway
          rsync -av --progress . ./cidgravitygateway --exclude node_modules --exclude .git --exclude cidgravitygateway --exclude .github --exclude .vscode
          zip -r cidgravitygateway-${{ github.ref_name }}.zip cidgravitygateway

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: cidgravitygateway-${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

